package typical

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/examples/generate-docker-compose/pinger"
	"github.com/typical-go/typical-go/pkg/typapp"
)

func init() {
	typapp.AppendConstructor(
		typapp.NewConstructor(pinger.NewRedisClient),
	)
}
