package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"log"

	"github.com/typical-go/typical-go/examples/typapp-sample/internal/app"
	_ "github.com/typical-go/typical-go/examples/typapp-sample/internal/generated/constructor"
	"github.com/typical-go/typical-go/pkg/typapp"
)

func main() {
	if err := typapp.Run(app.Start2, app.Shutdown); err != nil {
		log.Fatal(err)
	}
}
