package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"fmt"
	"log"

	"github.com/typical-go/typical-go/examples/typapp-sample/internal/app"
	"github.com/typical-go/typical-go/pkg/typapp"
	"github.com/typical-go/typical-go/pkg/typgo"

	_ "github.com/typical-go/typical-go/examples/typapp-sample/internal/generated/ctor"
)

func main() {
	fmt.Printf("%s %s\n", typgo.ProjectName, typgo.ProjectVersion)
	err := typapp.Run(app.Start2, app.Shutdown)
	if err != nil {
		log.Fatal(err)
	}
}
