package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"fmt"
	"log"

	"github.com/typical-go/typical-go/examples/my-project/internal/app"
	_ "github.com/typical-go/typical-go/examples/my-project/internal/generated/ctor"
	"github.com/typical-go/typical-go/pkg/typapp"
	"github.com/typical-go/typical-go/pkg/typgo"
)

func main() {
	fmt.Printf("%s %s\n", typgo.ProjectName, typgo.ProjectVersion)
	if err := typapp.StartService(app.Start, app.Stop); err != nil {
		log.Fatal(err)
	}
}
