package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"fmt"
	"log"
	"syscall"

	"github.com/typical-go/typical-go/examples/my-project/internal/app"
	_ "github.com/typical-go/typical-go/examples/my-project/internal/generated/ctor"
	"github.com/typical-go/typical-go/pkg/typapp"
	"github.com/typical-go/typical-go/pkg/typgo"
)

func main() {
	fmt.Printf("%s %s\n", typgo.ProjectName, typgo.ProjectVersion)

	application := typapp.Application{
		StartFn:    app.Start,
		ShutdownFn: app.Shutdown,
		ExitSigs:   []syscall.Signal{syscall.SIGTERM, syscall.SIGINT},
	}

	if err := application.Run(); err != nil {
		log.Fatal(err)
	}
}
