#!/bin/bash

set -e

TYPSRC=github.com/typical-go/typical-go/cmd/typical-go
TYPTMP=.typical-tmp
TYPGO=$TYPTMP/bin/typical-go

if ! [ -s $TYPGO ]; then
    go build -o $TYPGO $TYPSRC
fi

# Hack to override module package because the example 
# project want to use its parent directory as typical-go
# source. Module Package is module name in go.mod file 
# or working path if the project in $GOPATH
PROJPKG="github.com/typical-go/typical-go/examples/serve-react-demo"

$TYPGO wrap -tmp-folder=$TYPTMP -project-package=$PROJPKG
$TYPTMP/bin/build-tool $@