package typannot_test

import (
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/typical-go/typical-go/pkg/typannot"
)

func TestSignature(t *testing.T) {
	testnames := []struct {
		TestName string
		typannot.Signature
		Expected string
	}{
		{
			Signature: typannot.Signature{},
			Expected:  "Autogenerated by Typical-Go. DO NOT EDIT.\n",
		},
		{
			Signature: typannot.Signature{TagName: "@some-tag", Help: "some-help"},
			Expected: `Autogenerated by Typical-Go. DO NOT EDIT.

TagName:
	@some-tag

Help:
	some-help
`,
		},
	}
	for _, tt := range testnames {
		t.Run(tt.TestName, func(t *testing.T) {
			require.Equal(t, tt.Expected, tt.String())
		})
	}
}
