package typical

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/examples/configuration-with-invocation/server"
	"github.com/typical-go/typical-go/pkg/typapp"
	"github.com/typical-go/typical-go/pkg/typcore"
	"github.com/typical-go/typical-go/pkg/typdep"
)

func init() {
	typapp.AppendConstructor(
		typdep.NewConstructor(func(cfgMngr typcore.ConfigManager) (*server.Config, error) {
			cfg, err := cfgMngr.RetrieveConfig("APP")
			if err != nil {
				return nil, err
			}
			return cfg.(*server.Config), nil
		}),
	)
}
