package typical

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/examples/configuration-with-invocation/server"
	"github.com/typical-go/typical-go/pkg/typapp"
	"github.com/typical-go/typical-go/pkg/typcfg"
)

func init() {
	typapp.Provide(
		&typapp.Constructor{
			Name: "",
			Fn: func() (cfg *server.Config, err error) {
				cfg = new(server.Config)
				if err = typcfg.Process("SERVER", cfg); err != nil {
					return nil, err
				}
				return
			},
		},
	)
	typapp.Destroy()
}
