#!/bin/bash
set -e

CHECKSUM_DATA=$(cksum typical/descriptor.go)

if ! [ -s .typical-metadata/checksum ]; then
	mkdir -p .typical-metadata
	cksum typical/descriptor.go > .typical-metadata/checksum
else
	CHECKSUM_UPDATED=$([ "$CHECKSUM_DATA" == "$(cat .typical-metadata/checksum )" ] ; echo $?)
fi

if [ "$CHECKSUM_UPDATED" == "1" ] || ! [[ -f bin/typical-go-buildtool ]] ; then 
	echo $CHECKSUM_DATA > .typical-metadata/checksum
	echo "Compile Typical-Build"
	go build -o bin/typical-go-buildtool ./cmd/typical-go-buildtool
fi

./bin/typical-go-buildtool $@