#!/bin/bash

set -e

TYPSRC=github.com/typical-go/typical-go/cmd/typical-go
TYPTMP=.typical-tmp
TYPGO=$TYPTMP/bin/typical-go

if ! [ -s $TYPGO ]; then
	go build -o $TYPGO $TYPSRC
fi

$TYPGO wrap \
	-typical-tmp=$TYPTMP \
	-project-pkg="github.com/typical-go/typical-go" \

$TYPTMP/bin/build-tool $@
