#!/bin/bash

set -e

TYPTMP=.typical-tmp
TYPGO=$TYPTMP/bin/typical-go

if ! [ -s $TYPGO ]; then
	go build -o $TYPGO github.com/typical-go/typical-go/cmd/typical-go
fi

$TYPGO \
	-src="tools/typical-build" \
	-proj-pkg="github.com/typical-go/typical-go" \
	-typical-tmp=$TYPTMP \
	$@
