package tmpl

// MainData is data for main src template
type MainData struct {
	DescriptorPackage string
}

// BuildToolMain is template for main source for build tool
const BuildToolMain = `package main

import (
	"github.com/typical-go/typical-go/pkg/typcore"
	"{{.DescriptorPackage}}"
)

func main() {
	typcore.LaunchBuildTool(&typical.Descriptor)
}
`

// AppMain is template for main source for build tool
const AppMain = `package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"{{.DescriptorPackage}}"
	"github.com/typical-go/typical-go/pkg/typcore"
)

func main() {
	typcore.LaunchApp(&typical.Descriptor)
}
`
