#!/bin/bash

set -e

TYPTMP=.typical-tmp
TYPGO=$TYPTMP/bin/typical-go

if ! [ -s $TYPGO ]; then
	echo "Build typical-go"
	go build -o $TYPGO github.com/typical-go/typical-go/cmd/typical-go
fi

$TYPGO \
	-src="tools/typical-build" \
	-project-pkg="github.com/typical-go/typical-go/examples/configuration-with-invocation" \
	-typical-tmp=$TYPTMP \
	$@
