package main

import (
	"github.com/typical-go/typical-go/examples/generate-mock/internal/helloworld"
	"github.com/typical-go/typical-go/pkg/typapp"
)

// Autogenerated by Typical-Go. DO NOT EDIT.

func init() {
	typapp.Provide(
		&typapp.Constructor{Name: "", Fn: helloworld.GetWriter},
		&typapp.Constructor{Name: "", Fn: helloworld.NewGreeter},
	)
	typapp.Destroy()
}
