package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/examples/configuration-with-invocation/typical"
	"github.com/typical-go/typical-go/pkg/typcore"
)

func main() {
	typcore.RunApp(&typical.Descriptor)
}
