package golang

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/typical-go/typical-go/pkg/utility/coll"
)

// Source is source code recipe for generated.go in typical package
type Source struct {
	PackageName string
	Imports     coll.KeyStrings
	Structs     []Struct
	Init        *Function
}

// NewSource return new instance of SourceCode
func NewSource(pkgName string) *Source {
	return &Source{
		PackageName: pkgName,
		Init:        &Function{Name: "init"},
	}
}

func (r Source) Write(w io.Writer) (err error) {
	fmt.Fprint(w, "// Autogenerated by Typical-Go. DO NOT EDIT.\n\n")
	fmt.Fprintf(w, "package %s\n", r.PackageName)
	for _, ks := range r.Imports {
		fmt.Fprintln(w, ks.Format(importFormat))
	}
	for i := range r.Structs {
		r.Structs[i].Write(w)
	}
	if r.Init != nil && !r.Init.IsEmpty() {
		r.Init.Write(w)
	}
	return
}

// WriteToFile to write to file
func (r Source) WriteToFile(filename string) (err error) {
	var f *os.File
	if f, err = os.Create(filename); err != nil {
		return
	}
	defer f.Close()
	return r.Write(f)
}

// AddStruct to add struct
func (r *Source) AddStruct(structs ...Struct) *Source {
	r.Structs = append(r.Structs, structs...)
	return r
}

// AddImport to add import
func (r *Source) AddImport(pkg, alias string) *Source {
	r.Imports.Append(coll.KeyString{Key: pkg, String: alias})
	return r
}

func importFormat(key, s string) string {
	var b strings.Builder
	b.WriteString("import ")
	if key != "" {
		b.WriteString(key)
		b.WriteString(" ")
	}
	b.WriteString("\"")
	b.WriteString(s)
	b.WriteString("\"\n")
	return b.String()
}
