package typical

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/examples/generate-mock/helloworld"
	"github.com/typical-go/typical-go/pkg/typgo"
)

func init() {
	typgo.Provide(
		&typgo.Constructor{Name: "", Fn: helloworld.GetWriter},
		&typgo.Constructor{Name: "", Fn: helloworld.NewGreeter},
	)
	typgo.Destroy()
}
