// Autogenerated by Typical-Go. DO NOT EDIT.

package dependency

import "github.com/typical-go/typical-go/typical"

func init() {
	typical.Context.TestTargets.Add("./app")
	typical.Context.TestTargets.Add("./app/starter")
	typical.Context.TestTargets.Add("./app/stmt")
}
