package typapp_test

import (
	"io/ioutil"
	"os"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/typical-go/typical-go/pkg/execkit"
	"github.com/typical-go/typical-go/pkg/typannot"
	"github.com/typical-go/typical-go/pkg/typapp"
	"github.com/typical-go/typical-go/pkg/typgo"
)

func TestCtorAnnotation_Annotate(t *testing.T) {
	os.MkdirAll("cmd/some-project", 0777)

	unpatch := execkit.Patch([]*execkit.RunExpectation{})
	defer unpatch(t)
	defer os.RemoveAll("cmd/some-project")

	ctorAnnot := &typapp.CtorAnnotation{}
	ctx := &typannot.Context{
		Context: &typgo.Context{
			BuildSys: &typgo.BuildSys{
				Descriptor: &typgo.Descriptor{ProjectName: "some-project"},
			},
		},
		ASTStore: &typannot.ASTStore{
			Annots: []*typannot.Annot{
				{
					TagName: "@ctor",
					Decl:    &typannot.Decl{Name: "NewObject", Package: "pkg", Type: &typannot.FuncType{}},
				},
				{
					TagName:  "@ctor",
					TagParam: `name:"obj2"`,
					Decl:     &typannot.Decl{Name: "NewObject2", Package: "pkg2", Type: &typannot.FuncType{}},
				},
			},
		},
	}

	require.NoError(t, ctorAnnot.Annotate(ctx))

	b, _ := ioutil.ReadFile("cmd/some-project/ctor_annotated.go")
	require.Equal(t, `package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/pkg/typapp"
)

func init() { 
	typapp.AppendCtor(
		&typapp.Constructor{Name: "", Fn: pkg.NewObject},
		&typapp.Constructor{Name: "obj2", Fn: pkg2.NewObject2},
	)
}`, string(b))

}

func TestCtorAnnotation_Annotate_Predefined(t *testing.T) {
	unpatch := execkit.Patch([]*execkit.RunExpectation{})
	defer unpatch(t)
	defer os.Remove("some-target")

	ctorAnnot := &typapp.CtorAnnotation{
		TagName:  "@some-tag",
		Target:   "some-target",
		Template: "some-template",
	}
	ctx := &typannot.Context{
		Context: &typgo.Context{
			BuildSys: &typgo.BuildSys{
				Descriptor: &typgo.Descriptor{ProjectName: "some-project"},
			},
		},
		ASTStore: &typannot.ASTStore{
			Annots: []*typannot.Annot{
				{
					TagName: "@some-tag",
					Decl:    &typannot.Decl{Name: "NewObject", Package: "pkg", Type: &typannot.FuncType{}},
				},
			},
		},
	}

	require.NoError(t, ctorAnnot.Annotate(ctx))

	b, _ := ioutil.ReadFile("some-target")
	require.Equal(t, `some-template`, string(b))

}

func TestCtorAnnotation_Annotate_RemoveTargetWhenNoAnnotation(t *testing.T) {
	target := "some-target"
	defer os.Remove(target)
	ioutil.WriteFile(target, []byte("some-content"), 0777)
	ctorAnnot := &typapp.CtorAnnotation{Target: target}
	ctx := &typannot.Context{
		Context:  &typgo.Context{},
		ASTStore: &typannot.ASTStore{},
	}
	require.NoError(t, ctorAnnot.Annotate(ctx))
	_, err := os.Stat(target)
	require.True(t, os.IsNotExist(err))
}
