package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/examples/use-dependency-injection/internal/app"
	_ "github.com/typical-go/typical-go/examples/use-dependency-injection/internal/generated/typical"
	"github.com/typical-go/typical-go/pkg/typapp"
)

func main() {
	typapp.Start(app.Start2)
}
