package typast_test

import (
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/typical-go/typical-go/pkg/typast"
)

func TestSignature(t *testing.T) {
	testnames := []struct {
		TestName string
		typast.Signature
		Expected string
	}{
		{
			Signature: typast.Signature{},
			Expected:  "DO NOT EDIT. Autogenerated by Typical-Go",
		},
		{
			Signature: typast.Signature{TagName: "@some-tag"},
			Expected:  `DO NOT EDIT. This file generated due to '@some-tag' annotation`,
		},
	}
	for _, tt := range testnames {
		t.Run(tt.TestName, func(t *testing.T) {
			require.Equal(t, tt.Expected, tt.String())
		})
	}
}
