// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/typical-go/typical-go/pkg/typapp (interfaces: Provider)

// Package mock_typapp is a generated GoMock package.
package mock_typapp

import (
	gomock "github.com/golang/mock/gomock"
	typapp "github.com/typical-go/typical-go/pkg/typapp"
	reflect "reflect"
)

// MockProvider is a mock of Provider interface
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Constructors mocks base method
func (m *MockProvider) Constructors() []*typapp.Constructor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Constructors")
	ret0, _ := ret[0].([]*typapp.Constructor)
	return ret0
}

// Constructors indicates an expected call of Constructors
func (mr *MockProviderMockRecorder) Constructors() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Constructors", reflect.TypeOf((*MockProvider)(nil).Constructors))
}
