package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/examples/provide-constructor/internal/helloworld"
	"github.com/typical-go/typical-go/pkg/typapp"
)

func init() {
	typapp.AppendConstructor(
		&typapp.Constructor{Name: "", Fn: helloworld.HelloWorld},
		&typapp.Constructor{Name: "typical", Fn: helloworld.HelloTypical},
	)
}
