package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/examples/provide-constructor/internal/helloworld"
	"github.com/typical-go/typical-go/pkg/typapp"
)

func init() {
	typapp.AppendDestructor(
		&typapp.Destructor{Fn: helloworld.Close},
	)
}
