package main

import (
	"github.com/typical-go/typical-go/examples/provide-constructor/internal/helloworld"
	"github.com/typical-go/typical-go/pkg/typapp"
)

// Autogenerated by Typical-Go. DO NOT EDIT.

func init() {
	typapp.Provide(
		&typapp.Constructor{Name: "", Fn: helloworld.HelloWorld},
		&typapp.Constructor{Name: "typical", Fn: helloworld.HelloTypical},
	)
	typapp.Destroy(
		&typapp.Destructor{Fn: helloworld.Close},
	)
}
