package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/examples/get-config-from-descriptor/typical"
	"github.com/typical-go/typical-go/pkg/typcore"
)

func main() {
	typcore.LaunchApp(&typical.Descriptor)
}
