package tmpl

type AppMainData struct {
	TypicalPackage string
}

const AppMain = `package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"{{.TypicalPackage}}"
	"github.com/typical-go/typical-go/pkg/typcore"
)

func main() {
	typcore.RunApp(&typical.Descriptor)
}
`
