package main

import (
	"github.com/typical-go/typical-go/pkg/typapp"
	"github.com/typical-go/typical-go/wrapper"
)

// Autogenerated by Typical-Go. DO NOT EDIT.

func main() {
	typapp.Start(wrapper.Main)
}
