package main

import (
	"github.com/typical-go/typical-go/internal/app"
	"github.com/typical-go/typical-go/pkg/typapp"
)

// Autogenerated by Typical-Go. DO NOT EDIT.

func main() {
	typapp.Start(app.Main)
}
