package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/examples/generate-docker-compose/typical"
	"github.com/typical-go/typical-go/pkg/typgo"
)

func main() {
	typcore.LaunchApp(&typical.Descriptor)
}
