package typtmpl_test

import (
	"testing"

	"github.com/typical-go/typical-go/pkg/typtmpl"
)

func TestAppMain(t *testing.T) {
	testTemplate(t,
		testcase{
			Template: &typtmpl.AppMain{DescPkg: "some-package"},
			expected: `package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"some-package"
	"github.com/typical-go/typical-go/pkg/typcore"
)

func main() {
	typcore.LaunchApp(&typical.Descriptor)
}
`,
		},
	)

}
