package typtmpl

import (
	"io"
)

type (
	// CtorAnnotated template
	CtorAnnotated struct {
		Package string
		Imports []string
		Ctors   []*Ctor
	}
	// Ctor is constructor model
	Ctor struct {
		Name string `json:"name"`
		Def  string `json:"-"`
	}
)

//
// CtorAnnotated
//

const ctorGenerated = `package {{.Package}}

// Autogenerated by Typical-Go. DO NOT EDIT.

import ({{range $import := .Imports}}
	"{{$import}}"{{end}}
)

func init() { {{if .Ctors}}
	typapp.AppendCtor({{range $c := .Ctors}}
		&typapp.Constructor{Name: "{{$c.Name}}", Fn: {{$c.Def}}},{{end}}
	){{end}}
}`

// Execute app precondition template
func (t *CtorAnnotated) Execute(w io.Writer) (err error) {
	return Parse("ctorGenerated", ctorGenerated, t, w)
}
