package typtmpl_test

import (
	"testing"

	"github.com/typical-go/typical-go/pkg/typtmpl"
)

func TestCtorGenerated(t *testing.T) {
	testTemplate(t,
		testcase{
			testName: "common constructor",
			Template: &typtmpl.CtorGenerated{
				Package: "main",
				Imports: []string{"pkg1", "pkg2"},
				Ctors: []*typtmpl.Ctor{
					{Name: "", Def: "pkg1.NewFunction1"},
					{Name: "", Def: "pkg2.NewFunction2"},
				},
			},
			expected: `package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"pkg1"
	"pkg2"
)

func init() {
	typapp.Provide(
		&typapp.Constructor{Name: "", Fn: pkg1.NewFunction1},
		&typapp.Constructor{Name: "", Fn: pkg2.NewFunction2},
	)
}`,
		},
	)
}
