package typtmpl

import "io"

type (
	// CtorAnnotated template
	CtorAnnotated struct {
		Package string
		Imports []string
		Ctors   []*Ctor
	}
	// Ctor is constructor model
	Ctor struct {
		Name string
		Def  string
	}
)

const ctorGenerated = `package {{.Package}}

// Autogenerated by Typical-Go. DO NOT EDIT.

import ({{range $import := .Imports}}
	"{{$import}}"{{end}}
)

func init() { {{if .Ctors}}
	typapp.Provide({{range $c := .Ctors}}
		&typapp.Constructor{Name: "{{$c.Name}}", Fn: {{$c.Def}}},{{end}}
	){{end}}
}`

// Execute app precondition template
func (t *CtorAnnotated) Execute(w io.Writer) (err error) {
	return Execute("ctorGenerated", ctorGenerated, t, w)
}
