package typtmpl_test

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/typical-go/typical-go/pkg/typtmpl"
)

func TestDtorAnnotated(t *testing.T) {

	testcases := []struct {
		TestName string
		typtmpl.Template
		Expected string
	}{
		{
			TestName: "common constructor",
			Template: &typtmpl.DtorAnnotated{
				Package: "main",
				Imports: []string{"pkg1", "pkg2"},
				Dtors: []*typtmpl.Dtor{
					{Def: "pkg1.NewFunction1"},
				},
			},
			Expected: `package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"pkg1"
	"pkg2"
)

func init() { 
	typapp.AppendDtor(
		&typapp.Destructor{Fn: pkg1.NewFunction1},
	)
}`,
		},
	}

	for _, tt := range testcases {
		t.Run(tt.TestName, func(t *testing.T) {
			var out strings.Builder
			require.NoError(t, tt.Execute(&out))
			require.Equal(t, tt.Expected, out.String())
		})
	}

}
