package typtmpl

import (
	"io"
)

type (
	// DtorAnnotated template
	DtorAnnotated struct {
		Package string
		Imports []string
		Dtors   []*Dtor
	}
	// Dtor is destructor model
	Dtor struct {
		Def string
	}
)

//
// DtorAnnotated
//

const dtorAnnotated = `package {{.Package}}

// Autogenerated by Typical-Go. DO NOT EDIT.

import ({{range $import := .Imports}}
	"{{$import}}"{{end}}
)

func init() { {{if .Dtors}}
	typapp.AppendDtor({{range $d := .Dtors}}
		&typapp.Destructor{Fn: {{$d.Def}}},{{end}}
	){{end}}
}`

// Execute app precondition template
func (t *DtorAnnotated) Execute(w io.Writer) (err error) {
	return Parse("dtorGenerated", dtorAnnotated, t, w)
}
