package typtmpl

import "io"

type (
	// DtorGenerated template
	DtorGenerated struct {
		Package string
		Imports []string
		Dtors   []*Dtor
	}
	// Dtor is destructor model
	Dtor struct {
		Def string
	}
)

const dtorGenerated = `package {{.Package}}

// Autogenerated by Typical-Go. DO NOT EDIT.

import ({{range $import := .Imports}}
	"{{$import}}"{{end}}
)

func init() {
	typapp.Destroy({{range $d := .Dtors}}
		&typapp.Destructor{Fn: {{$d.Def}}},{{end}}
	)
}`

// Execute app precondition template
func (t *DtorGenerated) Execute(w io.Writer) (err error) {
	return Execute("dtorGenerated", dtorGenerated, t, w)
}
