package typtmpl

import (
	"io"
	"strings"
)

var _ Template = (*Precond)(nil)

const precond = `package {{.Package}}

// Autogenerated by Typical-Go. DO NOT EDIT.

import ({{range $import := .Imports}}
	"{{$import}}"{{end}}
)

func init() { {{range $line := .Lines}}
	{{$line}}{{end}}
}
`

// Precond writer
type Precond struct {
	Package string
	Imports []string
	Lines   []string
}

// AppendImport to append imports
func (i *Precond) AppendImport(imports ...string) {
	i.Imports = append(i.Imports, imports...)
}

// AppendLine to append init line
func (i *Precond) AppendLine(lines ...string) {
	i.Lines = append(i.Lines, lines...)
}

// AppendTemplate to append init line with wirter
func (i *Precond) AppendTemplate(tmpl Template) {
	var b strings.Builder
	tmpl.Execute(&b)
	i.AppendLine(b.String())
}

// Execute precond template
func (i *Precond) Execute(w io.Writer) (err error) {
	return Execute("precond", precond, i, w)
}
