package typtmpl_test

import (
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/typical-go/typical-go/pkg/typtmpl"
)

func TestPrecond(t *testing.T) {
	testTemplate(t,
		testcase{
			Template: &typtmpl.Precond{
				Package: "main",
				Imports: []string{"import1", "import2"},
				Lines:   []string{"line1", "line2"},
			},
			expected: `package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"import1"
	"import2"
)

func init() { 
	line1
	line2
}
`,
		},
	)

}

func TestPrecond_Append(t *testing.T) {
	precond := &typtmpl.Precond{}
	precond.AppendImport("import1", "import2")
	precond.AppendLine("line1", "line2")
	precond.AppendTemplate(&dummyTemplate{"template1"})

	require.Equal(t, &typtmpl.Precond{
		Imports: []string{"import1", "import2"},
		Lines:   []string{"line1", "line2", "template1"},
	}, precond)

}
