package typtmpl_test

import (
	"testing"

	"github.com/typical-go/typical-go/pkg/typtmpl"
)

func TestPrecond(t *testing.T) {
	testTemplate(t,
		testcase{
			Template: &typtmpl.Precond{
				Imports: []string{"import1", "import2"},
				Lines:   []string{"line1", "line2"},
			},
			expected: `package typical

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"import1"
	"import2"
)

func init() { 
	line1
	line2
}
`,
		},
	)

}
