package typical

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/examples/provide-constructor/helloworld"
	"github.com/typical-go/typical-go/pkg/typapp"
)

func init() {
	typapp.Provide(
		typapp.NewConstructor("", helloworld.HelloWorld),
		typapp.NewConstructor("typical", helloworld.HelloTypical),
	)
}
