package typfactory_test

import (
	"testing"

	"github.com/typical-go/typical-go/pkg/typfactory"
)

func TestAppMain(t *testing.T) {
	testWriter(t,
		testcase{
			Writer: &typfactory.AppMain{DescPkg: "some-package"},
			expected: `package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"some-package"
	"github.com/typical-go/typical-go/pkg/typcore"
)

func main() {
	typcore.LaunchApp(&typical.Descriptor)
}
`,
		},
	)

}
