package typfactory_test

import (
	"strings"
	"testing"

	"github.com/typical-go/typical-go/pkg/typfactory"

	"github.com/stretchr/testify/require"
)

func TestAppMain(t *testing.T) {
	testcases := []testcase{
		{
			Writer: &typfactory.AppMain{DescPkg: "some-package"},
			expected: `package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"some-package"
	"github.com/typical-go/typical-go/pkg/typcore"
)

func main() {
	typcore.LaunchApp(&typical.Descriptor)
}
`,
		},
	}
	for _, tt := range testcases {
		var debugger strings.Builder
		require.NoError(t, tt.Write(&debugger))
		require.Equal(t, tt.expected, debugger.String())
	}
}
