package typfactory

import (
	"io"
	"text/template"
)

const appMain = `package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"{{.DescPkg}}"
	"github.com/typical-go/typical-go/pkg/typcore"
)

func main() {
	typcore.LaunchApp(&typical.Descriptor)
}
`

// AppMain is writer to generate main.go for app
type AppMain struct {
	DescPkg string
}

// Write the tyicalw
func (t *AppMain) Write(w io.Writer) (err error) {
	var tmpl *template.Template
	if tmpl, err = template.New("").Parse(appMain); err != nil {
		return
	}
	return tmpl.Execute(w, t)
}
