package typfactory

import (
	"io"
	"strings"
	"text/template"
)

const initialApp = `package typical

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/pkg/typapp"{{range $import := .Imports}}
	"{{$import}}"{{end}}
)

func init() { {{range $line := .Lines}}
	{{$line}}{{end}}
}
`

// InitialApp writer
type InitialApp struct {
	Imports []string
	Lines   []string
}

// NewInitialApp return new instance of InitialApp
func NewInitialApp(imports ...string) *InitialApp {
	return &InitialApp{
		Imports: imports,
	}
}

// Append to append init line
func (i *InitialApp) Append(line string) {
	i.Lines = append(i.Lines, line)
}

// AppendWithWriter to append init line with wirter
func (i *InitialApp) AppendWithWriter(w Writer) {
	var b strings.Builder
	w.Write(&b)
	i.Append(b.String())
}

// Write the tyicalw
func (i *InitialApp) Write(w io.Writer) (err error) {
	var tmpl *template.Template
	if tmpl, err = template.New("").Parse(initialApp); err != nil {
		return
	}
	return tmpl.Execute(w, i)
}
