package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/typical-go/typical-go/examples/use-config/internal/server"
	"github.com/typical-go/typical-go/pkg/typapp"
	"github.com/typical-go/typical-go/pkg/typgo"
)

func init() {
	typapp.AppendCtor(
		&typapp.Constructor{
			Name: "",
			Fn: func() (cfg *server.Config, err error) {
				cfg = new(server.Config)
				if err = typgo.ProcessConfig("SERVER", cfg); err != nil {
					return nil, err
				}
				return
			},
		},
	)
}
