package main

// Autogenerated by Typical-Go. DO NOT EDIT.

import (
	"github.com/kelseyhightower/envconfig"
	"github.com/typical-go/typical-go/examples/use-config/internal/server"
	"github.com/typical-go/typical-go/pkg/typapp"
)

func init() {
	typapp.AppendCtor(
		&typapp.Constructor{
			Name: "",
			Fn: func() (*server.Config, error) {
				var cfg server.Config
				if err := envconfig.Process("CONFIG", &cfg); err != nil {
					return nil, err
				}
				return &cfg, nil
			},
		},
	)
}
