package main

import (
	"github.com/typical-go/typical-go/examples/use-config/internal/server"
	"github.com/typical-go/typical-go/pkg/typapp"
)

// Autogenerated by Typical-Go. DO NOT EDIT.

func main() {
	typapp.Start(server.Main)
}
